[bot]
    token = "DISCORD BOT TOKEN HERE"
    prefix = "!"
    server = 0
    server_name = "My Server"
    owners = [ # Owners of the bot
        0,
        1
    ]
    admins = [ # Administrators of the bot
        0,
        1
    ]
    blacklist = [ # Blacklisted users from using the bot
        0,
        1
    ]

[database] # Database configuration
    name = "PyBot"