[bot]
    token = "DISCORD BOT TOKEN HERE"
    prefix = "!"
    server = 0
    server_name = "My Server"
    owners = [ # Owners of the bot
        0,
        1
    ]
    admins = [ # Administrators of the bot
        0,
        1
    ]
    blacklist = [ # Blacklisted users from using the bot
        0,
        1
    ]

[database] # Database configuration
    name = "PyBot"

[mineminenomi] # Configuration of mineminenomi mod
    [mineminenomi.ftp] # FTP Connection
        host = "ftpserver.com"
        port = 22
        user = "username"
        password = "password"

    [mineminenomi.rcon] # Rcon Connection
        host = "play.server.com"
        port = 30130
        password = "password"

    [mineminenomi.devil_fruits]
        panel_channel =  0

    [mineminenomi.races]
        cyborg =         0
        fishman =        0
        human =          0
        mink =           0

    [mineminenomi.factions]
        bounty_hunter =  0
        marine =         0
        pirate =         0
        revolutionary =  0

    [mineminenomi.fighting_styles]
        art_of_weather = 0
        black_leg =      0
        brawler =        0
        doctor =         0
        sniper =         0
        swordsman =      0

    [mineminenomi.crews]
        category =       0
